### ISSUE TITLE
Google Analytics (gtag.js) example is using legacy analytics.

### ISSUE THREAD

**Issue by workeffortwaste** [Accudio/cead-consent#4]
It looks like the **Google Analytics (gtag.js)** example is actually using the legacy analytics implementation ga.js. The example needs updating to reflect the current gtag.js implementation.

https://developers.google.com/analytics/devguides/collection/gtagjs

**Comment by Accudio** [comment]
Thanks for letting me know!

Had a bit of a content mix-up just before launch shuffling around the examples. I thought I'd fixed everything but evidently that slipped through.

Good eye!
